const employees = [
  {
    id: 1,
    name: "Aarav Sharma",
    email: "employee1@example.com",
    password: "123",
    tasks: [
      {
        title: "Prepare Monthly Report",
        description: "Compile the data for the monthly financial report.",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        date: "2024-11-20",
        category: "Finance",
      },
      {
        title: "Team Meeting",
        description: "Discuss project progress with the team.",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        date: "2024-11-22",
        category: "Management",
      },
      {
        title: "Fix Website Bug",
        description: "Resolve the issue on the login page.",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        date: "2024-11-18",
        category: "Development",
      },
    ],
    taskCounts: {
      active: 2,
      newTask: 1,
      completed: 1,
      failed: 0,
    },
  },
  {
    id: 2,
    name: "Ishita Patel",
    email: "employee2@example.com",
    password: "123",
    tasks: [
      {
        title: "Update Documentation",
        description: "Review and update project documentation.",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        date: "2024-11-19",
        category: "Documentation",
      },
      {
        title: "Prepare Presentation",
        description: "Create slides for the client presentation.",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        date: "2024-11-23",
        category: "Client Work",
      },
      {
        title: "Design Mockups",
        description: "Create mockups for the new feature.",
        active: true,
        newTask: false,
        completed: false,
        failed: true,
        date: "2024-11-15",
        category: "Design",
      },
    ],
    taskCounts: {
      active: 2,
      newTask: 1,
      completed: 1,
      failed: 1,
    },
  },
  {
    id: 3,
    name: "Rajesh Kumar",
    email: "employee3@example.com",
    password: "123",
    tasks: [
      {
        title: "Test API Integration",
        description: "Test the new API integration with the frontend.",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        date: "2024-11-17",
        category: "Testing",
      },
      {
        title: "Deploy Application",
        description: "Deploy the application to the production server.",
        active: false,
        newTask: true,
        completed: false,
        failed: true,
        date: "2024-11-18",
        category: "DevOps",
      },
      {
        title: "Code Review",
        description: "Review the code changes submitted by the team.",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        date: "2024-11-21",
        category: "Development",
      },
    ],
    taskCounts: {
      active: 1,
      newTask: 1,
      completed: 1,
      failed: 1,
    },
  },
  {
    id: 4,
    name: "Neha Singh",
    email: "employee4@example.com",
    password: "123",
    tasks: [
      {
        title: "Create Social Media Plan",
        description: "Develop a plan for next month's social media posts.",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        date: "2024-11-20",
        category: "Marketing",
      },
      {
        title: "Customer Feedback Analysis",
        description: "Analyze feedback from the recent survey.",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        date: "2024-11-19",
        category: "Research",
      },
      {
        title: "Onboarding New Intern",
        description: "Help the new intern settle into their role.",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        date: "2024-11-21",
        category: "HR",
      },
    ],
    taskCounts: {
      active: 2,
      newTask: 1,
      completed: 1,
      failed: 0,
    },
  },
  {
    id: 5,
    name: "Ananya Rao",
    email: "employee5@example.com",
    password: "123",
    tasks: [
      {
        title: "Database Optimization",
        description: "Optimize database queries for better performance.",
        active: false,
        newTask: true,
        completed: false,
        failed: true,
        date: "2024-11-20",
        category: "Database",
      },
      {
        title: "Write Blog Post",
        description: "Draft a new blog post for the company website.",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        date: "2024-11-22",
        category: "Content",
      },
      {
        title: "Conduct Training Session",
        description: "Conduct a training session on new software tools.",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        date: "2024-11-18",
        category: "Training",
      },
    ],
    taskCounts: {
      active: 1,
      newTask: 1,
      completed: 1,
      failed: 1,
    },
  },
];

const admin = [
  {
    id: 1,
    email: "admin@me.com",
    password: "123",
  },
];

export const setLocalStorage = () => {
  // localStorage.setItem("employees", JSON.stringify(employees));
  // localStorage.setItem("admin", JSON.stringify(admin));
};
export const getLocalStorage = () => {
  const employees = JSON.parse(localStorage.getItem("employees"));
  const admin = JSON.parse(localStorage.getItem("admin"));
  return { employees, admin };
};